version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nyk-email-system"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cy83wcld8wf5"
s3_prefix = "nyk-email-system"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

